"""
cheatsheet.py, one page, task first, with the real command name baked in.
=========================================================================

Generated by the installer into the course folder as CHEATSHEET.md and
CHEATSHEET.pdf, and regenerated by `config` when the course code is
confirmed. Written for a professor standing at a terminal in week 1 with a
class waiting: every line is a command they can type, organized by what
they are trying to do, with no explanation of why. The why is the README's
job.

THE PDF
    Written by hand, below, with no library: a single page of text set in
    the PDF base-14 fonts (Helvetica-Bold for headings, Courier for
    commands), which every PDF reader has built in, so nothing is embedded
    and nothing is downloaded. Text is encoded as WinAnsi so accented names
    survive. About sixty lines fit; the sheet uses fewer. If it ever does
    not fit, cut content rather than shrinking the type.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Tuple

from . import config as cfg

# (kind, text). kind: "title", "h", "cmd", "note", "blank"
# {c} is the command name.


def lines(course: cfg.Course) -> List[Tuple[str, str]]:
    c = course.course
    g = course.data.get("grading") or f"~/{c}-grading"
    L: List[Tuple[str, str]] = []
    add = L.append
    add(("title", f"{c}  cheatsheet    {course.title}    org {course.org}"))
    add(("blank", ""))
    add(("h", "SETTING UP AN ASSIGNMENT"))
    add(("cmd", f"{c} new a04                      make the folders, pick auto or manual"))
    add(("cmd", f"{c} verify a04                   check it before anyone sees it"))
    add(("cmd", f"{c} template a04 --go            push the starter to GitHub"))
    add(("cmd", f"{c} assign a04 --go              create every student's repository"))
    add(("blank", ""))
    add(("h", "DURING THE ASSIGNMENT"))
    add(("cmd", f"{c}                              what is out of step, and what to run"))
    add(("cmd", f"{c} ui                           the same thing in a browser"))
    add(("cmd", f"{c} students import form.csv     merge new GitHub usernames"))
    add(("cmd", f"{c} patch a04                    preview a fix to a do-not-edit file"))
    add(("cmd", f"{c} patch a04 --go               push it to everyone"))
    add(("cmd", f"{c} patch a04 --missing --go     add starter files the repos do not have yet"))
    add(("cmd", f"{c} access a04 --go             let your grader read every student repository"))
    add(("blank", ""))
    add(("h", "GRADING"))
    add(("cmd", f"{c} marks a04                    run the autograder, write the gradebook"))
    add(("cmd", f"{c} collect a04                  just download everyone's work"))
    add(("cmd", f"{c} sheet a04                    a CSV to type marks into"))
    add(("note", 'add --as-of "2026-10-14T23:59:59-04:00" to grade what existed at the deadline'))
    add(("blank", ""))
    add(("h", "WHEN SOMETHING IS WRONG"))
    add(("cmd", f"{c} doctor                       check everything at once"))
    add(("cmd", f"{c} doctor --smoke --go          push one job and see it run, queue or fail"))
    add(("cmd", f"{c} config                       show every setting"))
    add(("cmd", f"{c} config --check               test GitHub, the org, and the runners"))
    add(("cmd", f"{c} config runner NEW-NAME       change one"))
    add(("blank", ""))
    add(("h", "THREE THINGS TO KNOW"))
    add(("note", "Nothing changes GitHub without --go."))
    add(("note", "Never push a file students have edited. patch will refuse; let it."))
    add(("note", "The green tick is not the grade. marks and sheet are."))
    add(("blank", ""))
    add(("h", "WHERE THINGS LIVE"))
    w = max(31, len(g) + 6)
    add(("cmd", "assignments/a04/starter/".ljust(w) + "exactly what the student gets"))
    add(("cmd", "assignments/a04/answers/".ljust(w) + "your solution, never published"))
    add(("cmd", "autograders/a04/".ljust(w) + "the grading bundle, never published"))
    add(("cmd", f"{g}/a04/".ljust(w) + "everything that comes back"))
    add(("cmd", "course.json".ljust(w) + "every setting; course-history.log says what changed"))
    return L


def markdown(course: cfg.Course) -> str:
    out = []
    block: List[str] = []

    def flush():
        if block:
            out.append("```")
            out.extend(block)
            out.append("```")
            block.clear()

    for kind, text in lines(course):
        if kind == "title":
            out.append(f"# {text}")
            out.append("")
            out.append("Every line is a command you can type. Nothing changes GitHub without `--go`.")
        elif kind == "h":
            flush()
            out.append("")
            out.append(f"## {text}")
            out.append("")
        elif kind in ("cmd", "note"):
            block.append(("  " if kind == "note" else "") + text)
        elif kind == "blank":
            flush()
    flush()
    out.append("")
    out.append(f"Course folder: `{course.root}`. Long versions: the toolkit's `docs/` folder.")
    return "\n".join(out) + "\n"


# ── the PDF writer ───────────────────────────────────────────────────

def _pdf_escape(text: str) -> bytes:
    data = text.encode("cp1252", errors="replace")
    return data.replace(b"\\", b"\\\\").replace(b"(", b"\\(").replace(b")", b"\\)")


def pdf_bytes(course: cfg.Course) -> bytes:
    """A one-page PDF, Letter size, of the cheatsheet lines."""
    width, height = 612, 792
    left, top = 40, 750
    content: List[bytes] = []
    y = top
    fonts = {"title": ("F1", 14), "h": ("F1", 11), "cmd": ("F2", 9.6), "note": ("F3", 9.5), "blank": ("F3", 6)}
    leading = {"title": 22, "h": 15, "cmd": 12.8, "note": 12.5, "blank": 6}
    for kind, text in lines(course):
        font, size = fonts[kind]
        if kind != "blank":
            x = left + (12 if kind == "note" else 0)
            content.append(b"BT /%s %s Tf %d %.1f Td (%s) Tj ET" % (
                font.encode(), str(size).encode(), x, y, _pdf_escape(text)))
        y -= leading[kind]
    footer = f"{course.title} · generated by ./install · keep this beside the keyboard"
    content.append(b"BT /F3 7.5 Tf %d 28 Td (%s) Tj ET" % (left, _pdf_escape(footer)))
    stream = b"\n".join(content)

    objects: List[bytes] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    objects.append(b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 %d %d] /Contents 4 0 R "
                   b"/Resources << /Font << /F1 5 0 R /F2 6 0 R /F3 7 0 R >> >> >>" % (width, height))
    objects.append(b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream")
    for name in (b"Helvetica-Bold", b"Courier", b"Helvetica"):
        objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /" + name +
                       b" /Encoding /WinAnsiEncoding >>")

    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % i + obj + b"\nendobj\n"
    xref = len(out)
    out += b"xref\n0 %d\n0000000000 65535 f \n" % (len(objects) + 1)
    for off in offsets:
        out += b"%010d 00000 n \n" % off
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (len(objects) + 1, xref)
    return bytes(out)


def write(course: cfg.Course) -> Tuple[Path, Path]:
    md = course.root / "CHEATSHEET.md"
    pdf = course.root / "CHEATSHEET.pdf"
    md.write_text(markdown(course), encoding="utf-8")
    pdf.write_bytes(pdf_bytes(course))
    return md, pdf
